### ISSUE TITLE
[BUG] Abstract content bar don't work correct.

### ISSUE THREAD

**Issue by kpatzwald** [Nacandev/Ohmine-Dark-Theme-For-Joplin#13]
**1. Where did you meet the bug? (delete whichever is inapplicable)**

- Markdown Editor

**2. Describe the bug**

The "Abstract Content Bar" don't display unorderd lists, images and checklists.

**3. To Reproduce**
Create an empty note. Add a list and a checklist. The lists aren't shown in the abstract content bar.

**4. Expected behavior**

The lists should be displayed in the abstract content bar.

**5. Screenshots**

![Bildschirmfoto 2022-02-20 um 16 22 04](https://user-images.githubusercontent.com/73938015/154849983-a001406c-c45e-4d5a-9545-e0749f0e7190.png)

**Comment by kpatzwald** [comment]
Sorry, after installing all plugins it works.

**Comment by Nacandev** [comment]
Oh! You made it! Thank you for supporting OhmineDT! 🥂
