### ISSUE TITLE
Display issue in notebooks titles when combining emojis and text (v. 3.1.4)

### ISSUE THREAD

**Issue by Estamin** [Nacandev/Ohmine-Dark-Theme-For-Joplin#15]
Windows 11
Joplin 2.7.13
Ohmine-Dark-Theme 3.1.4

***

Hi @Nacandev,
Thank you for this great theme. It really helps me.
I think that there is a display issue with latest update (3.1.4), in the notebook panel, in notebook names, when combining text and emojis : useless indentation created between emoji and text + notecount is not aligned

![image](https://user-images.githubusercontent.com/66172934/156874416-e52e99a8-40b2-40e1-8fa4-99a1f21c95df.png)

**Comment by Nacandev** [comment]
Hi @Estamin, I'm sorry about that! I've already released a quick fix for this problem. Let me know if you have any other problems. Thank you for supporting OhmineDT! 😄

**Comment by Estamin** [comment]
thank you for fixing this so quickly !

> Let me know if you have any other problems

well, I don't know if this is a problem but... are these parenthesis normal between links and hyperlinks ?
![image](https://user-images.githubusercontent.com/66172934/156892718-d9e1d4af-689e-441d-b8aa-8bcedc77c3bd.png)

**Comment by Nacandev** [comment]
Oh! It's normal, I didn't turn the whole link to Monospace font in the Render Viewer. I only give it the Monospace brackets for emphasizing the links, so you will see that it is like this. Whatever, it's just decoration for links. If you don't want it, you can switch off this feature by editing your `userstyle.css`.

For reference: [Line 45 of userstyle.css](https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin/blob/1784218fdc36dbea01aedf624afddee0241c0d45/userstyle.css#L45)

1. Open Joplin
2. Go to `tools' > `options` > `appearance` > `Show Advanced Settings`
3. Click `Custom stylesheet for rendered Markdown` to open your `userstyle.css`
4. Go to line 47
5. Edit the `--switcher-link-bracket-display: inline;` change to `--switcher-link-bracket-display: none;`. 
6. Save it and restart Joplin, and you will see it work!

**Comment by Estamin** [comment]
perfect ! thank you for your help ! keep on this great work !
