### ISSUE TITLE
[feature-request] solid block header line style

### ISSUE THREAD

**Issue by hihihlo** [Nacandev/Ohmine-Dark-Theme-For-Joplin#16]
Is it possible to highlight whole header line with solid block background color ?
below is my EmEditor (a text editor) screenshot, my ideal is look like it :
![image](https://user-images.githubusercontent.com/10369189/161670944-1ca5c7e2-5eb4-4ca6-a300-8ffc85dff566.png)

below Joplin CSS by tatoosh is very close to the ideal :
https://discourse.joplinapp.org/t/share-your-css/1730/20

but I can't let it work in Ohmine Dark Theme
(primarily apply to markdown editor rather than rich WYSIWYG editor),

if I add below to userchrome.css
```
div.CodeMirror .cm-header {
  border: 1px solid #777 !important;
  border-top: 1px solid #777;
  border-bottom: 1px solid #777;
  border-left: 1px solid #777;
  border-right: 1px solid #777;
  display: inline;
}
```
it look like : (not whole line)
![image](https://user-images.githubusercontent.com/10369189/161671011-d1420bf2-9c52-46cc-a9e1-8f22b9bfb50a.png)

if I change from `display: inline` to `display: block`,
it look like : (whole line but split into multi-lines !)
![image](https://user-images.githubusercontent.com/10369189/161671037-ec262193-a6b9-4ddc-bbd8-e1b59d3c5d35.png)

(sorry I lake CSS knowledge)
Could you mind add a theme version of such style ?
I’m very grateful.

**Comment by Nacandev** [comment]
Hi @hihihlo, I think I won't add this style to OhmineDT at the moment, but I'm happy to give you a hand. Please copy the below code and paste it to the bottom of your `userchrome.css` file.

```
/* ********************************************************* */
/* vvvvvvvvv             CUSTOM CODE              vvvvvvvvvv */
/* ********************************************************* */

/* header background --------------------------------------- */
[class^="cm-header"].cm-overlay.cm-rm-header-token {
  background: #1d5a4f;
  float: left;
}
[class^="cm-header"] {
  display: block;
  line-height: normal !important;
  background: #3f8677;
}
```
Here is the markdown viewer preview:

![Screenshot 2022-04-05 131731](https://user-images.githubusercontent.com/86870826/161683916-fee05fdf-b15d-4f55-b4f1-5ea3bc48303a.png)

Is it what you need?

**Comment by hihihlo** [comment]
Yes, your CUSTOM CODE is indeed works !
Your help is greatly appreciated.
Thank you very nuch~

**Comment by Nacandev** [comment]
Thank you for supporting OhmineDT! 😀
