### ISSUE TITLE
[help-wanted] How do you remove the double spaces?

### ISSUE THREAD

**Issue by an0wak** [Nacandev/Ohmine-Dark-Theme-For-Joplin#19]
Hi, quick question, after a header or before code box how do you remove the paragraph gap.
Highlighted in red?

![KT7dCcwz47](https://user-images.githubusercontent.com/74270857/169231009-708da433-2051-4310-a17f-917479f070e3.png)
?

**Comment by Nacandev** [comment]
Hi @an0wak, all the block elements have their own margin on them. So, that gap is relevant to a few elements below:

- headings
- paragraph
- horizontal line
- list
- codeblock
- blockquote
- table

If you want to remove the gap between `heading` and `codeblock` you should edit both of their margins. I wrote two versions of the codes for you, you can choose the one you like, and then copy & paste it to the bottom of your `userstyle.css`:

1. The first version is to remove all margins as you request, you won't see any gap between them.

```
/* paragraph margin ---------------------------------------- */
#rendered-md > p {
  padding: 0;
  margin: 0 0 0 3px;
}

/* horizontal line margin ---------------------------------- */
#rendered-md > hr {
  margin: 0;
}

/* heading margin ------------------------------------------ */
#rendered-md > h1,
#rendered-md > h2,
#rendered-md > h3,
#rendered-md > h4,
#rendered-md > h5,
#rendered-md > h6 {
  margin: 0;
}

/* list margin --------------------------------------------- */
#rendered-md ul,
#rendered-md ol {
  margin: 0 0 0 25px;
}

/* table margin -------------------------------------------- */
#rendered-md > table {
  margin: 0 auto;
}

/* blockquote margin --------------------------------------- */
#rendered-md > blockquote {
  margin: 0 0 0 5px;
}

/* codeblock margin ---------------------------------------- */
#rendered-md > .joplin-editable > pre:not(.mermaid) {
  margin: 0;
}

```

2. The second version is set 10px margin for them. Just in case you need a little bit of margin between them.

```
/* paragraph margin ---------------------------------------- */
#rendered-md > p {
  padding: 0;
  margin: 10px 0 10px 3px;
}

/* horizontal line margin ---------------------------------- */
#rendered-md > hr {
  margin: 10px 0;
}

/* heading margin ------------------------------------------ */
#rendered-md > h1,
#rendered-md > h2,
#rendered-md > h3,
#rendered-md > h4,
#rendered-md > h5,
#rendered-md > h6 {
  margin: 10px 0;
}

/* list margin --------------------------------------------- */
#rendered-md ul,
#rendered-md ol {
  margin: 10px 0 10px 25px;
}

/* table margin -------------------------------------------- */
#rendered-md > table {
  margin: 10px auto;
}

/* blockquote margin --------------------------------------- */
#rendered-md > blockquote {
  margin: 10px 0 10px 5px;
}

/* codeblock margin ---------------------------------------- */
#rendered-md > .joplin-editable > pre:not(.mermaid) {
  margin: 10px 0;
}

```

**Comment by an0wak** [comment]
Hi Nacandev, I really appreciate you creating the css for me ... just seem to be struggling getting it to work. I will look at it again and see what I am doing wrong.  I'll let you know how I go. Cheers!!

**Comment by an0wak** [comment]
Hi Nacandev,

Looks like I got it to work just by replacing the existing components. Pasting to the bottom of css did not seem to work.
I have couple more for you :). I seem to have some strange vertical line circled in red. Is there a way to use the entire window space? I know this may effect the scrollbars. I also noticed the mouse wheel does not work on scrollable items.

![image](https://user-images.githubusercontent.com/74270857/171299058-70aabb39-e2b6-41f1-a1b0-73e8bf1f96bb.png)
 
BTW awesome theme - easy on the eyes!

**Comment by Nacandev** [comment]
Hi @an0wak , Good to hear from you again! 

1. "Pasting to the bottom of css did not seem to work"

All the CSS code I have tested before I give it to you, so I make sure it worked perfectly. (If you didn't edit the main source code section earlier) Please make sure you are using the latest version of OhmineDT and paste the custom code at the bottom of `userstyle.css`, and it will only change the margin gap which appeared on the Render Viewer. Just add the code like below:

- Once you make any change to the css, you should quit and restart Joplin to get work.
- Please note that, if you've edited the main source code section, it will make me couldn't figure out the exact problem.

![Screenshot 2022-06-01 113203](https://user-images.githubusercontent.com/86870826/171322338-a802f544-7975-47fe-96c2-73c172971653.png)

---

2. "I seem to have some strange vertical line circled in red"

- This is an Abstract Content Bar, it's one of the features which OhmineDT creates for you. [See what's it for](https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin#abstract-content-bar)
- If you don't think it's useful for you, you can turn it off by editing the `--switcher-mde-abstract-content-bar-display` which is on the `userchrome.css`. [where is it?](https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin/blob/6f55cb4767af0063e04cde107337ca40d943fad1/userchrome.css#L32)

---

3. "Is there a way to use the entire window space?"

This margin gap is not from OhmineDT, you can go to `toos` > `options` > `appearance` > `editor maximum width` and change it to zero.

![Screenshot 2022-06-01 120327](https://user-images.githubusercontent.com/86870826/171325188-f9b91e76-5ef8-4683-9800-2e75a7323c31.png)

---

4. " I also noticed the mouse wheel does not work on scrollable items."

I can't be sure why you have this problem. It's all working well for me.

---

Whatever, if you finally can't solve the problem, you can just let me see all your codes from the `userstyle.css` and `userchrome.css` and I will solve it for you.

**Comment by an0wak** [comment]
Perfect! exactly what I wanted and information I was looking for! 
Really appreciate the quick response.
