### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yezichu** [Nacandev/Ohmine-Dark-Theme-For-Joplin#20]
How does Codeblock look like a picture
![1653398363(1)](https://user-images.githubusercontent.com/73242472/170045213-785d7f4c-72c8-442a-aa9a-ae48117716c0.jpg)
This is mine
![image](https://user-images.githubusercontent.com/73242472/170045346-c376b7ea-f2ed-4107-a8b2-214a44db22de.png)
No borders or highlighting

**Comment by Nacandev** [comment]
Hi @yezichu ! Sorry for the late reply. And ya, just like @3ter said, you should use the 3 backticks markdown syntax to create the code block. Thank you for using OhmineDT!

---

@3ter , thank you for helping reply!😃 It's surprising me! 🎉 ❤️
