### ISSUE TITLE
[help] The size of the formula

### ISSUE THREAD

**Issue by yezichu** [Nacandev/Ohmine-Dark-Theme-For-Joplin#21]
After I exported it to PDF, I found that all the inter-line formulas are very large. May I ask how to modify the formulas to become smaller?

**Comment by Nacandev** [comment]
There are two methods for converting a note to PDF and please make sure you are using the `Export PDF` if you are expecting the inline elements to be allowed to select. When using the `Print PDF` method, all the contents seem protected by a filter and not allowed to be selected. 

Actually, I'm not so sure what you mean by "the inter-line formulas are very large", in case you are urgent, I'm just trying to guess it first. If my reply can't solve your problem, please provide the image and more details for me,
