### ISSUE TITLE
[feature-request] Make this theme a plugin

### ISSUE THREAD

**Issue by 3ter** [Nacandev/Ohmine-Dark-Theme-For-Joplin#4]
I'm really enjoying this theme but I'd like to be able to switch back and forth easily.
What do you think about packing it as a plugin like the [macOS-Theme](https://github.com/ajilderda/joplin-macos-native-theme) did?

Thanks for all your magical `important!` CSS efforts :slightly_smiling_face: .

**Comment by Nacandev** [comment]
I'm still not enough understanding the Joplin plugin at the moment, it seems there are some limitations when building a theme as a plugin. Whatever, I think I will give it a try in the future but I can't guarantee that I'll finally release it or when. It's all depends on which is more customizable for users. 

At this moment, I'm considering the three options of below:

1. Keep `userstyle.css` and `userchrome.css` only
2. Plugin only
3. Plugin + `userstyle.css` and `userchrome.css`

Glad you like OhmineDT and thank you for let me know what your expecting of it!

**Comment by Nacandev** [comment]
I close this post first, but I will keep that in mind.
