### ISSUE TITLE
[BUG] Mermaid background

### ISSUE THREAD

**Issue by cnburke** [Nacandev/Ohmine-Dark-Theme-For-Joplin#5]
**1. Where did you meet the bug? (delete whichever is inapplicable)**
- Render Viewer

**2. Describe the bug**

Mermaid graph background is dark based on the CSS background for code blocks. While I like the background being dark, the rest of the CSS for mermaid is also dark.

**3. To Reproduce**

Add a note with the following in a mermaid code block and view the result in the render viewer (note the double quotes, had to add them here so they would show up:

graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;

**4. Expected behavior**

White background for the graph. Unless you want to dive in to all the different supported mermaid graph types and update the dozens of CSS styles for all the subcomponents :D

**5. Screenshots**

![image](https://user-images.githubusercontent.com/22404077/140323307-161a3b63-969a-435f-8e52-cceba8527ae0.png)

**Comment by Nacandev** [comment]
Ok, I got it, it'll be fix in the next update. I was really want to write CSS for all Mermaid functions but I found that there is already have some built-in syntax for customize the Mermaid charts. So, I'm don't have to do that now. 😄  Thank you for your report!

In case you are urgent, you can follow the below steps to edit your `userstyle.css` by yourself before I released the next updates:

1. You may see the below code in the line 543 to 555 (OhmineDT v2.0.1), this code is for the code block styling
2. The only thing you have to do is to add a few words on the second line
3. `.joplin-editable > pre {` change to `.joplin-editable > pre:not(.mermaid) {`
4. Quit and Restart Joplin and it's done!

```
  /* code block -------------------------------------------- */
  .joplin-editable > pre {
    line-height: var(--code-block-line-height); 
    padding: 10px 12px;
    margin: 20px 0;
    background: var(--code-block-background);
    border-width: 0 2px;
    border-style: ridge;
    border-color: var(--code-block-border);
    border-radius: 8px;
    box-shadow: 0 0 3px var(--code-block-box-shadow);
    overflow-y: scroll;
  }
```

Please make sure your final output is same as below:

```
  /* code block -------------------------------------------- */
  .joplin-editable > pre:not(.mermaid) {
    line-height: var(--code-block-line-height); 
    padding: 10px 12px;
    margin: 20px 0;
    background: var(--code-block-background);
    border-width: 0 2px;
    border-style: ridge;
    border-color: var(--code-block-border);
    border-radius: 8px;
    box-shadow: 0 0 3px var(--code-block-box-shadow);
    overflow-y: scroll;
  }
```

**Comment by cnburke** [comment]
Works wonderfully! Thank you so much for the quick response. Again, this is a great theme!
