### ISSUE TITLE
[BUG] Abstract Content Bar appears in the wrong place in code block

### ISSUE THREAD

**Issue by cnburke** [Nacandev/Ohmine-Dark-Theme-For-Joplin#6]
**1. Where did you meet the bug? (delete whichever is inapplicable)**

- Markdown Editor

**2. Describe the bug**

Something fishy going on with the abstract content bar for code blocks in the editor - it's hitting at the end of the line rather than staying on the right column of the editor pane

**3. To Reproduce**

Joplin v2.5.10 w/ v2.01 OhmineDT

Make a code block. Put something in it. 

**4. Expected behavior**

Abstract content bar lines stay where they're supposed to go. 

**5. Screenshots**

![image](https://user-images.githubusercontent.com/22404077/140788354-441be4da-b520-4956-b62d-f37358634cbb.png)

**PS**
Thanks again! I've been sharing this theme with others and they all love it. You should throw a buy me a coffee link on your page.

**Comment by Nacandev** [comment]
Okay, I found it, and it will be fixed with the latest update within 2 days.

Buy me a coffee? 🤔 No, I owe you one, because it is always a lot more than a coffee while you are sharing my theme! Thank you for your enthusiasm for OhmineDT! 😄

**Comment by cnburke** [comment]
Thanks!
