### ISSUE TITLE
[BUG] Line wrap issue for notebook names in Joplin 2.6.9

### ISSUE THREAD

**Issue by Klemet** [Nacandev/Ohmine-Dark-Theme-For-Joplin#8]
**1. Where did you meet the bug? (delete whichever is inapplicable)**

- Notebook Panel

**2. Describe the bug**

In Joplin 2.6.9, it seems that when the name of a notebook is too long, it doesn't wrap, or doesn't display `...` to cut it. Instead, the line wraps "on itself", making things unreadable. This is the case for v2.2.15 of the theme.

**3. To Reproduce**

1. Install Joplin 2.6.9
2. Customize the css of Joplin with v2.2.15 of the theme

**4. Expected behavior**

The name of the notebooks should wrap up as was the case pre Joplin 2.6.9.

**5. Screenshots**

![image](https://user-images.githubusercontent.com/41070328/146624758-cbf5d12c-5c61-4654-a993-8cf55df6ae68.png)

**Comment by Nacandev** [comment]
Thank you! And it's fixed in the v2.2.16 which I just released. 😃

**Comment by Klemet** [comment]
Talk about responsive 😄 ! v2.2.16 works like a charm, thank you so much !
