### ISSUE TITLE
[BUG] unnecessary white space after special chararacter apostrophe (')

### ISSUE THREAD

**Issue by Estamin** [Nacandev/Ohmine-Dark-Theme-For-Joplin#9]
**1. Where did you meet the bug?**

- Markdown Editor

**2. Describe the bug**

Ohmine Dark Theme creates an unnecessary white space after special chararacter apostrophe (').

**3. To Reproduce**

1. Install Joplin desktop version
2. Customize the css of Joplin with Ohmine Dark Theme
3. see that Ohmine Dark Theme creates an unnecessary white space after special chararacter apostrophe (').

**4. Expected behavior**

No unnecessary white space should appear after an apostrophe (').

**5. Screenshots**
![image](https://user-images.githubusercontent.com/66172934/148658364-1cc0da2d-9eeb-40d7-bea9-789939f1e84d.png)

**Comment by Nacandev** [comment]
Hi @Estamin, sorry for late reply. I'm not sure what's problem is it but I've been met the same problem when I using the Microsoft JengHei font for English characters. 

So, I think you better to download and install the recommended fonts for the theme. (Montserrat and Cascadia)

Or, you can edit my CSS code to customize whatever fonts you want. 

Please let me know if you need any help, thank you for supporting OhmineDT! 😊

**Comment by Estamin** [comment]
Oh OK, I may have failed at installing Montserrat and Cascadia properly. I will try again and let you know ASAP.

Thank you for your help and for this great theme.

**Comment by Estamin** [comment]
> So, I think you better to download and install the recommended fonts for the theme. (Montserrat and Cascadia)
> https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin#requirements-of-ohmine-dark-theme

well, it was as simple as that...
thank you again
have a good day !
